name: thrilme
description: ThrilMe - Your personal emotional wellness companion.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.1
  go_router: ^8.2.0
  supabase_flutter: ^1.2.0
  web_socket_channel: ^2.4.5
  uuid: ^4.0.0
  http: ^1.0.0
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.0.0
  emoji_picker_flutter: ^2.0.0
  cached_network_image: ^3.3.0
  video_player: ^2.8.0
  audioplayers: ^5.2.0
  intl: ^0.19.0
  flutter_local_notifications: ^17.0.0
  image_picker: ^0.8.7
  record: ^6.0.0

  permission_handler: ^11.0.0
  timeago: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

dependency_overrides:
  sign_in_with_apple: ^6.0.0
